# Generated by Django 2.0.6 on 2018-09-27 09:16

from django.db import migrations, models
import django.db.models.deletion
import station.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('netdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('decomissioned', models.BooleanField(default=False, verbose_name='Decomissioned')),
                ('decomissioned_date', models.DateField(default='2023-12-31')),
                ('hostname', models.CharField(default=None, max_length=7, verbose_name='Site ID')),
                ('location', models.CharField(default=None, max_length=100, verbose_name='Site Location')),
                ('site_name', models.CharField(default=None, max_length=100, verbose_name='Site Name')),
                ('g4', models.BooleanField(default=False, help_text='Check this field, if it is G2/G4 station', verbose_name='G4 station')),
                ('gras', models.BooleanField(default=False, help_text='Check this field, if it is GRAS station', verbose_name='GRAS station')),
                ('antenna_brand', models.CharField(choices=[('SEPTENTRIO', 'SEPTENTRIO'), ('TRIMBLE', 'TRIMBLE')], default=None, max_length=100, verbose_name='Antenna brand')),
                ('antenna_type', models.CharField(choices=[('TRM55971.00', 'TRM55971.00'), ('TRM57971.00', 'TRM57971.00'), ('SEPCHOKE_B3E6', 'SEPCHOKE_B3E6'), ('TRM1155000.10', 'TRM1155000.10')], default=None, max_length=100, verbose_name='Antenna type')),
                ('antenna_sn', models.CharField(default=None, max_length=50, verbose_name='Antenna Serial Number')),
                ('has_radome', models.BooleanField(default=False, help_text='Check this field, if the antenna has radome', verbose_name='Atenna with radome')),
                ('receiver_brand', models.CharField(choices=[('SEPTENTRIO', 'SEPTENTRIO'), ('TRIMBLE', 'TRIMBLE')], default=None, max_length=100, verbose_name='Receiver brand')),
                ('receiver_type', models.CharField(choices=[('NETR9', 'NETR9'), ('NETR5', 'NETR5'), ('POLARX5', 'POLARX5')], default=None, max_length=100, verbose_name='Receiver type')),
                ('receiver_sn', models.CharField(default=None, max_length=50, verbose_name='Receiver Serial Number')),
                ('company_asset_number', models.CharField(max_length=30, verbose_name='Company Asset Number')),
                ('manufacture_year', models.IntegerField(default=None, verbose_name='Year of manufacture')),
                ('warranty', models.CharField(default=None, max_length=100, verbose_name='Warranty status')),
                ('os', models.CharField(default=None, max_length=100, verbose_name='Firmware')),
                ('ip_v4_address', models.CharField(default=None, max_length=30, verbose_name='GNSS receiver private ipv4 address')),
                ('ip_v4_address_public', models.CharField(default=None, max_length=100, verbose_name='GNSS receiver public ipv4 address')),
                ('internet_connection_type', models.CharField(default=None, max_length=30, verbose_name='Internet connection type')),
                ('bandwidth', models.CharField(default=None, max_length=20, verbose_name='Download/Upload')),
                ('file_picture_1', models.FileField(blank=True, default=None, upload_to=station.models.save_directory_path, verbose_name='Site Diagram')),
                ('file_picture_2', models.FileField(blank=True, default=None, upload_to=station.models.save_directory_path, verbose_name='Antenna Picture')),
                ('file_other', models.FileField(blank=True, default=None, upload_to=station.models.save_directory_path, verbose_name='Other file/Zip file if many')),
                ('site_contact', models.CharField(default=None, max_length=100, verbose_name='Site contact')),
                ('other', models.TextField(default=None, max_length=500, verbose_name='Notes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('site_router_ip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='netdev.Netdev')),
            ],
            options={
                'verbose_name_plural': 'Stations',
            },
        ),
    ]
